### ISSUE TITLE
issue if the message is a buffer

### ISSUE THREAD

**Issue by fanfare** [GertSallaerts/ws-transform-stream#1]
thanks for all of your work on this plugin. I managed to get this working with no problem if the 'message' being transformed is a string. I ran into a snag when the incoming message to be processed was a buffer, though. I figure this is probably some issue with how the `ws` module is processing a binary message maybe. Even if the `transform` function is like:
```
transform(message) {
    return message
}
```
it doesn't seem to transparently pass along the buffer. Just wanted to run this by you in case there's some kind of super simple solution. Thanks again.

**Comment by GertSallaerts** [comment]
I'll try to look into it. Can you send me an example to make it easier?

At first glance, there shouldn't be anything in my code that would prevent the message that's received by the `ws` receiver to be passed to the transform function. Maybe you could try playing around with this option: https://github.com/websockets/ws/blob/master/doc/ws.md#websocketbinarytype

You can pass it to my library like this: `new WsTransformStream({ receiver: { binaryType: '...' } });`

**Comment by fanfare** [comment]
Thanks for pointing me to that. i figured that would do the trick (the library I'm using happens to be using 'arraybuffer', which was not the default) but even with changing `receiver` to `arraybuffer` I still couldn't get it going. It's pretty hard to isolate this problem; I'm trying to use this with noVNC, and it has its own [websocket library](https://github.com/novnc/noVNC/blob/master/core/websock.js) that seems like it's doing a bunch of things with buffering, etc. I think this is possibly a dead end but I'll keep messing with it, and at any rate, thank you for the help.
